use_frameworks!

platform :ios, '9.0'

target 'LSMoyaTool_Example' do
  pod 'LSMoyaTool', :path => '../'
  
  pod 'Moya/RxSwift'
  
  target 'LSMoyaTool_Tests' do
    inherit! :search_paths

    
  end
end
